[package]
name = "wasabi"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A terminal typing test."
repository = "https://github.com/doohed/wasabi"

[dependencies]
ratatui = "0.30"
color-eyre = "0.6"
rand = "0.10.2"
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }
